version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPERADMIN_CHAT_ID=${SUPERADMIN_CHAT_ID}  # Добавляем переменную
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: telegram_bot_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: